{"name": "test_sum2[4-7-10]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 11 == 10\n +  where 11 = sum(4, 7)", "trace": "self = <testcases.test_example.Test_Data object at 0x03FA9850>, x = 4, y = 7\nz = 10\n\n    @pytest.mark.parametrize('x,y,z',params)\n    def test_sum2(self,x,y,z):\n>       assert sum(x,y)==z\nE       assert 11 == 10\nE        +  where 11 = sum(4, 7)\n\ntestcases\\test_example.py:23: AssertionError"}, "parameters": [{"name": "x", "value": "4"}, {"name": "y", "value": "7"}, {"name": "z", "value": "10"}], "start": 1615688380740, "stop": 1615688380741, "uuid": "0594de20-cad1-4ee5-995e-416634e393e2", "historyId": "894969370444bd15910f80d79b79e6d6", "testCaseId": "e2880f9a3efb130b4a5cf71404b74e0b", "fullName": "testcases.test_example.Test_Data#test_sum2", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_example"}, {"name": "subSuite", "value": "Test_Data"}, {"name": "host", "value": "NO-47"}, {"name": "thread", "value": "18452-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_example"}]}